### ISSUE TITLE
W:18 Invalid character in group name

### ISSUE THREAD

**Issue by SandWoodJones** [p00f/nvim-ts-rainbow#18]
The editor throws this message as soon as it displays any `()` or `{}` with rainbow turned on. This started happening after updating to `NVIM v0.5.0-dev+1197-ga17782042`

**Comment by p00f** [comment]
It was https://github.com/neovim/neovim/commit/06c065469b12a3a8088b812380db612a9984c45f, I'll try to find out

**Comment by p00f** [comment]
I can't reproduce it anymore :neutral_face:

**Comment by harrygallagher4** [comment]
Looks to be caused by [this](https://github.com/p00f/nvim-ts-rainbow/blob/34e859ab43998bc107eae7fa022c52e3a7e43e13/lua/rainbow/internal.lua#L77) since that neovim change you linked made some changes to the metatable of `hl_map`. I'm not sure what the purpose of that line in `internal.lua` is anyway, I commented it out and now there's no error & rainbow brackets are working fine.

**Comment by p00f** [comment]
Ah yes I needed it earlier because treesitter highlighting had a higher priority and it highlighted lua `{}` because it is a table constructor

**Comment by p00f** [comment]
If I remember correctly, that is. Let's hope nothing breaks
